(define (problem task01)
	(:domain transport)
	(:objects r1 - robot l1 l2 l3 l4 - location)
	(:init 
		;(road l1 l2)
		(road l1 l4)
		(road l4 l2)
		(road l2 l3)
		(road l3 l4)
		(at r1 l1)
		(accessPoint l4)
                (= (power r1) 10)
		(= (time) 0)
		(= (knowlOf l1) 0)
		(= (knowlOf l2) 0)
		(= (knowlOf l3) 0)
		(= (knowlOf l4) 0)
	)
	(:goal (and (infoSent l2) (> (power r1) 0))
	)
	(:metric maximize (power r1))
        
        
)
