(define (problem Venezia)
	(:domain RFIStation)
	(:objects
	)
	(:init
		(trainEntersStationAt T1 F11)
		(trainEntersStationAt T2 F10)
		(trainEntersStationAt T3 F7)
		(trainEntersStationAt T4 F4)
		(trainEntersStationAt T5 F5)
		(= (time ) 0)
		(= (timeElapsedReservedItinerary I6-12) 0)
		(= (timeElapsedReservedItinerary I7-8) 0)
		(= (timeElapsedReservedItinerary I8-01) 0)
		(= (timeElapsedReservedItinerary I8-02) 0)
		(= (timeElapsedReservedItinerary I8-03) 0)
		(= (timeElapsedReservedItinerary I8-04) 0)
		(= (timeElapsedReservedItinerary I8-05) 0)
		(= (timeElapsedReservedItinerary I8-VIII) 0)
		(= (timeElapsedReservedItinerary I8-VII) 0)
		(= (timeElapsedReservedItinerary I8-VI) 0)
		(= (timeElapsedReservedItinerary I9-01) 0)
		(= (timeElapsedReservedItinerary I9-02) 0)
		(= (timeElapsedReservedItinerary I9-04) 0)
		(= (timeElapsedReservedItinerary I9-05) 0)
		(= (timeElapsedReservedItinerary I9-VIII) 0)
		(= (timeElapsedReservedItinerary I9-VII) 0)
		(= (timeElapsedReservedItinerary I9-VI) 0)
		(= (timeElapsedReservedItinerary I10-01) 0)
		(= (timeElapsedReservedItinerary I10-02) 0)
		(= (timeElapsedReservedItinerary I10-03) 0)
		(= (timeElapsedReservedItinerary I10-04) 0)
		(= (timeElapsedReservedItinerary I10-05) 0)
		(= (timeElapsedReservedItinerary I10-VIII) 0)
		(= (timeElapsedReservedItinerary I10-VII) 0)
		(= (timeElapsedReservedItinerary I10-VI) 0)
		(= (timeElapsedReservedItinerary I11-01) 0)
		(= (timeElapsedReservedItinerary I11-02) 0)
		(= (timeElapsedReservedItinerary I11-03) 0)
		(= (timeElapsedReservedItinerary I11-04) 0)
		(= (timeElapsedReservedItinerary I11-05) 0)
		(= (timeElapsedReservedItinerary I11-VIII) 0)
		(= (timeElapsedReservedItinerary I11-VII) 0)
		(= (timeElapsedReservedItinerary I11-VI) 0)
		(= (timeElapsedReservedItinerary I12-01) 0)
		(= (timeElapsedReservedItinerary I12-02) 0)
		(= (timeElapsedReservedItinerary I12-03) 0)
		(= (timeElapsedReservedItinerary I12-04) 0)
		(= (timeElapsedReservedItinerary I12-05) 0)
		(= (timeElapsedReservedItinerary I12-VIII) 0)
		(= (timeElapsedReservedItinerary I12-VII) 0)
		(= (timeElapsedReservedItinerary I12-VI) 0)
		(= (timeElapsedReservedItinerary I1-01) 0)
		(= (timeElapsedReservedItinerary I1-02) 0)
		(= (timeElapsedReservedItinerary I1-03) 0)
		(= (timeElapsedReservedItinerary I1-04) 0)
		(= (timeElapsedReservedItinerary I1-05) 0)
		(= (timeElapsedReservedItinerary I1-VIII) 0)
		(= (timeElapsedReservedItinerary I1-VII) 0)
		(= (timeElapsedReservedItinerary I1-VI) 0)
		(= (timeElapsedReservedItinerary I2-01) 0)
		(= (timeElapsedReservedItinerary I2-02) 0)
		(= (timeElapsedReservedItinerary I2-03) 0)
		(= (timeElapsedReservedItinerary I2-04) 0)
		(= (timeElapsedReservedItinerary I2-05) 0)
		(= (timeElapsedReservedItinerary I2-VIII) 0)
		(= (timeElapsedReservedItinerary I2-VII) 0)
		(= (timeElapsedReservedItinerary I2-VI) 0)
		(= (timeElapsedReservedItinerary I4-01) 0)
		(= (timeElapsedReservedItinerary I4-02) 0)
		(= (timeElapsedReservedItinerary I4-03) 0)
		(= (timeElapsedReservedItinerary I4-04) 0)
		(= (timeElapsedReservedItinerary I4-05) 0)
		(= (timeElapsedReservedItinerary I4-VIII) 0)
		(= (timeElapsedReservedItinerary I4-VII) 0)
		(= (timeElapsedReservedItinerary I4-VI) 0)
		(= (timeElapsedReservedItinerary I5-01) 0)
		(= (timeElapsedReservedItinerary I5-02) 0)
		(= (timeElapsedReservedItinerary I5-03) 0)
		(= (timeElapsedReservedItinerary I5-04) 0)
		(= (timeElapsedReservedItinerary I5-05) 0)
		(= (timeElapsedReservedItinerary I5-VIII) 0)
		(= (timeElapsedReservedItinerary I5-VII) 0)
		(= (timeElapsedReservedItinerary I5-VI) 0)
		(= (timeElapsedReservedItinerary I01-1) 0)
		(= (timeElapsedReservedItinerary I01-2) 0)
		(= (timeElapsedReservedItinerary I01-4) 0)
		(= (timeElapsedReservedItinerary I01-5) 0)
		(= (timeElapsedReservedItinerary I02-1) 0)
		(= (timeElapsedReservedItinerary I02-4) 0)
		(= (timeElapsedReservedItinerary I02-5) 0)
		(= (timeElapsedReservedItinerary I03-1) 0)
		(= (timeElapsedReservedItinerary I03-2) 0)
		(= (timeElapsedReservedItinerary I03-4) 0)
		(= (timeElapsedReservedItinerary I03-5) 0)
		(= (timeElapsedReservedItinerary I04-1) 0)
		(= (timeElapsedReservedItinerary I04-2) 0)
		(= (timeElapsedReservedItinerary I04-4) 0)
		(= (timeElapsedReservedItinerary I04-5) 0)
		(= (timeElapsedReservedItinerary I05-1) 0)
		(= (timeElapsedReservedItinerary I05-2) 0)
		(= (timeElapsedReservedItinerary I05-4) 0)
		(= (timeElapsedReservedItinerary I05-5) 0)
		(= (timeElapsedReservedItinerary IVIII-1) 0)
		(= (timeElapsedReservedItinerary IVIII-2) 0)
		(= (timeElapsedReservedItinerary IVIII-4) 0)
		(= (timeElapsedReservedItinerary IVIII-5) 0)
		(= (timeElapsedReservedItinerary IVII-1) 0)
		(= (timeElapsedReservedItinerary IVII-2) 0)
		(= (timeElapsedReservedItinerary IVII-4) 0)
		(= (timeElapsedReservedItinerary IVII-5) 0)
		(= (timeElapsedReservedItinerary IVI-1) 0)
		(= (timeElapsedReservedItinerary IVI-2) 0)
		(= (timeElapsedReservedItinerary IVI-4) 0)
		(= (timeElapsedReservedItinerary IVI-5) 0)
		(= (timeElapsedReservedItinerary I01-6) 0)
		(= (timeElapsedReservedItinerary I01-7) 0)
		(= (timeElapsedReservedItinerary I01-9) 0)
		(= (timeElapsedReservedItinerary I01-10) 0)
		(= (timeElapsedReservedItinerary I01-11) 0)
		(= (timeElapsedReservedItinerary I02-6) 0)
		(= (timeElapsedReservedItinerary I02-7) 0)
		(= (timeElapsedReservedItinerary I02-9) 0)
		(= (timeElapsedReservedItinerary I02-10) 0)
		(= (timeElapsedReservedItinerary I02-11) 0)
		(= (timeElapsedReservedItinerary I03-6) 0)
		(= (timeElapsedReservedItinerary I03-7) 0)
		(= (timeElapsedReservedItinerary I03-9) 0)
		(= (timeElapsedReservedItinerary I03-10) 0)
		(= (timeElapsedReservedItinerary I03-11) 0)
		(= (timeElapsedReservedItinerary I04-6) 0)
		(= (timeElapsedReservedItinerary I04-7) 0)
		(= (timeElapsedReservedItinerary I04-9) 0)
		(= (timeElapsedReservedItinerary I04-10) 0)
		(= (timeElapsedReservedItinerary I04-11) 0)
		(= (timeElapsedReservedItinerary I05-6) 0)
		(= (timeElapsedReservedItinerary I05-7) 0)
		(= (timeElapsedReservedItinerary I05-9) 0)
		(= (timeElapsedReservedItinerary I05-10) 0)
		(= (timeElapsedReservedItinerary I05-11) 0)
		(= (timeElapsedReservedItinerary IFM-6) 0)
		(= (timeElapsedReservedItinerary IFM-7) 0)
		(= (timeElapsedReservedItinerary IFM-9) 0)
		(= (timeElapsedReservedItinerary IFM-10) 0)
		(= (timeElapsedReservedItinerary IFM-11) 0)
		(= (timeElapsedReservedItinerary IVIII-6) 0)
		(= (timeElapsedReservedItinerary IVIII-7) 0)
		(= (timeElapsedReservedItinerary IVIII-9) 0)
		(= (timeElapsedReservedItinerary IVIII-10) 0)
		(= (timeElapsedReservedItinerary IVIII-11) 0)
		(= (timeElapsedReservedItinerary IVII-6) 0)
		(= (timeElapsedReservedItinerary IVII-7) 0)
		(= (timeElapsedReservedItinerary IVII-9) 0)
		(= (timeElapsedReservedItinerary IVII-10) 0)
		(= (timeElapsedReservedItinerary IVII-11) 0)
		(= (timeElapsedReservedItinerary IVI-6) 0)
		(= (timeElapsedReservedItinerary IVI-7) 0)
		(= (timeElapsedReservedItinerary IVI-9) 0)
		(= (timeElapsedReservedItinerary IVI-10) 0)
		(= (timeElapsedReservedItinerary IVI-11) 0)
		(= (timeElapsedReservedItinerary I02-2) 0)
		(= (timeElapsedReservedItinerary I9-03) 0)
		(= (timeElapsedOverlappedFlag F6) 0)
		(= (timeElapsedOverlappedFlag F12) 0)
		(= (timeElapsedOverlappedFlag F7) 0)
		(= (timeElapsedOverlappedFlag F8) 0)
		(= (timeElapsedOverlappedFlag F01TV) 0)
		(= (timeElapsedOverlappedFlag F02TV) 0)
		(= (timeElapsedOverlappedFlag F03TV) 0)
		(= (timeElapsedOverlappedFlag F04TV) 0)
		(= (timeElapsedOverlappedFlag F05TV) 0)
		(= (timeElapsedOverlappedFlag FVIIITV) 0)
		(= (timeElapsedOverlappedFlag FVIITV) 0)
		(= (timeElapsedOverlappedFlag FVITV) 0)
		(= (timeElapsedOverlappedFlag F9) 0)
		(= (timeElapsedOverlappedFlag F10) 0)
		(= (timeElapsedOverlappedFlag F11) 0)
		(= (timeElapsedOverlappedFlag F1) 0)
		(= (timeElapsedOverlappedFlag F01VI) 0)
		(= (timeElapsedOverlappedFlag F02VI) 0)
		(= (timeElapsedOverlappedFlag F03VI) 0)
		(= (timeElapsedOverlappedFlag F04VI) 0)
		(= (timeElapsedOverlappedFlag F05VI) 0)
		(= (timeElapsedOverlappedFlag FVIIIVI) 0)
		(= (timeElapsedOverlappedFlag FVIIVI) 0)
		(= (timeElapsedOverlappedFlag FVIVI) 0)
		(= (timeElapsedOverlappedFlag F2) 0)
		(= (timeElapsedOverlappedFlag F4) 0)
		(= (timeElapsedOverlappedFlag F5) 0)
		(= (timeElapsedOverlappedFlag FFM) 0)
		(= (trainStayInStation T1) 0)

		(= (trainStayInStation T2) 0)

		(= (trainStayInStation T3) 0)

		(= (trainStayInStation T4) 0)

		(= (trainStayInStation T5) 0)
		(= (trainArrivalTime T1) 8)
		(= (trainArrivalTime T2) 14)
		(= (trainArrivalTime T3) 25)
		(= (trainArrivalTime T4) 1)
		(= (trainArrivalTime T5) 17)
	)
	(:goal
		(and
			(<= (trainStayInStation T1) 20)
			(trainExitsStationAt T1 F2)
			(trainHasStopped T1)
			(trainHasStoppedAtStop T1 S_IV)
			(<= (trainStayInStation T2) 20)
			(trainExitsStationAt T2 F2)
			(trainHasStopped T2)
			(trainHasStoppedAtStop T2 S_IV)
			(<= (trainStayInStation T3) 20)
			(trainExitsStationAt T3 F2)
			(<= (trainStayInStation T4) 20)
			(trainExitsStationAt T4 F9)
			(<= (trainStayInStation T5) 20)
			(trainExitsStationAt T5 F9)
		)
	)
)
