(define (control-knowledge ck1) (:domain blocks) (:problem blocks-4-0)
    (:temporal-constraints
        (and
            (t-forall (?x - (pick-up b))
                (t-forall (?y - (stack  b a))
                    (>= (- ?y ?x) 10)
                )
            )
            (t-forall (?x - (pick-up c))
                (t-forall (?y - (stack  c b))
                    (>= (- ?y ?x) 10)
                )
            )
            (t-forall (?x - (pick-up d))
                (t-forall (?y - (stack  d c))
                    (>= (- ?y ?x) 10)
                )
            )
        )
    )
)